### ISSUE TITLE
db issue on last version

### ISSUE THREAD

**Issue by blackwizard-BE** [ThybeVB/ActionCommandGame-FirefighterAdventure#1]
what is the admin db password needed for changing the background via ui?

**Comment by ThybeVB** [comment]
![Screenshot_5](https://github.com/ThybeVB/ActionCommandGame-FirefighterAdventure/assets/30873388/95618c23-f84e-479d-beee-23378dfd47e2)

**Comment by ThybeVB** [comment]
![Schermafbeelding 2024-05-26 143442](https://github.com/ThybeVB/ActionCommandGame-FirefighterAdventure/assets/30873388/7d42edb4-17f0-4058-a74a-1feade0f6eaa)

**Comment by blackwizard-BE** [comment]
![Screenshot from 2024-05-26 21-54-26](https://github.com/ThybeVB/ActionCommandGame-FirefighterAdventure/assets/75219159/4c16031b-98f1-4512-9708-28834b9997ce)

**Comment by ThybeVB** [comment]
![image](https://github.com/ThybeVB/ActionCommandGame-FirefighterAdventure/assets/30873388/3c15da61-1c88-4600-ab7b-67fcc815e300)

**Comment by blackwizard-BE** [comment]
![image](https://github.com/ThybeVB/ActionCommandGame-FirefighterAdventure/assets/75219159/42b358e5-5144-452f-8679-db5be098b6d5)

**Comment by blackwizard-BE** [comment]
damn fucked up
